### ISSUE TITLE
Can't make it to work

### ISSUE THREAD

**Issue by inlacou** [txomon/tuenti-downloader#1]
Mensaje de error:

`INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api-msngr.tuenti.com`
`INFO:root:Users 1/1`
`INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): imrl.tuenti.net`
`Traceback (most recent call last):`
`File "td.py", line 152, in <module>`
`main()`
`File "td.py", line 146, in main`
`file_downloader.save_photo(photo)`
`File "td.py", line 63, in save_photo`
`if self.download_file(file_uri, file_path):`
`File "td.py", line 48, in download_file`
`with open(file_path, 'wb') as f:`
`IOError: [Errno 2] No such file or directory: u'dl/1ciOz9Xb6qLsx5wX_A5-q2QA.jpg'`

Cabe destacar que, debido a que no dispongo de la libreria libgexiv2, he tenido que borrar el try catch relacionado con ella.

**Comment by taniarv** [comment]
Ídem, mismo error

**Comment by jomaceld** [comment]
Creando la carpeta "dl" a mano se soluciona. 
O especificando en la linea 49 una carpeta que exista donde se descargaran las fotos.

**Comment by inlacou** [comment]
Gracias @jomaceld.

Ahora, en mi caso, obtengo el error:

Traceback (most recent call last):
  File "td.py", line 152, in <module>
    main()
  File "td.py", line 146, in main
    file_downloader.save_photo(photo)
  File "td.py", line 65, in save_photo
    update_ts(file_path, ts)
  File "td.py", line 71, in update_ts
    ef = exiv_file(file)
NameError: global name 'exiv_file' is not defined

¿Puede ser por mi forma de eliminar el uso de la librería libgexiv2?

**Comment by jomaceld** [comment]
@Inlacou 

Si, exiv_file parece que forma parte de la librería GExiv2. 
En mi caso (Ubuntu) se ha solucionado instalando el paquete gir1.2-gexiv2-0.10 con apt-get.  
`sudo apt-get install gir1.2-gexiv2-0.10`

Deberias buscar la forma de instalar GExiv2 en el sistema en el que estés.

Otra solución seria no usar GExiv2. Quitando como ya has hecho el try catch del inicio y comentando la siguiente linea creo que seria suficiente:

`# update_ts(file_path, ts)`

**Comment by txomon** [comment]
Buenas!

Esto es un error que te da no tener la librería, en teoría había hecho que gexiv2 no fuera obligatorio (se pierde la funcionalidad de los timestamps), pero no consigo reproducir el error. Puedes comprobar con la versión que acabo de subir?

recuerda hacer python setup.py install otra vez!

La parte de las descargas la arreglo en el commit que acabo de subir 57aa310a857af93078a8241b9e343ef92b002b4f

**Comment by txomon** [comment]
@Inlacou El try catch estaba para evitar que te saltára la excepción de no tener la librería. Hay casos en los que la imagen descargada es inválida. Y el try catch hace que no falle la ejecución del programa.

Por favor comprobad que funciona con el último commit y procedo a cerrar el issue

**Comment by inlacou** [comment]
Acabo de hacer un clone de nuevo y este es el error que me salta (el mismo que me saltaba antes de eliminar el try-catch:

Traceback (most recent call last):
  File "td.py", line 12, in <module>
    gi.require_version('GExiv2', '0.10')
  File "/usr/lib/python2.7/dist-packages/gi/**init**.py", line 48, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GExiv2 not available

Eliminando el try-catch y la linea `update_ts(file_path, ts)`, como comenta @jomaceld, realiza la descarga de fotos sin mayores problemas con lo que ya es muy, muy util.

De todos modos, quizás convendría mirarlo para que el resto de la gente no deba leer esta issue para hacerlo funcionar ^^

**Comment by fravalpin** [comment]
a mi me funciona :-) aunque el setup me lo he tenido que hacer yo a manita buscando las librerias. Y sobre lo del timestamps no veo ninguna evidencia sobre lo descargado.
Buen trabajo de todos modos ;-) gracias!

Edit\* -> PD: no es de esta ultima versión de hace 20 mins

**Comment by txomon** [comment]
Ah joder, claro, es que el problema lo estaba solucionando para el import, no me saltaba el ValueError... Voy a hacer un except para eso y listo. 1 Sec...

**Comment by txomon** [comment]
Nuevo commit, esta vez tendría que funcionar porque he hecho un except para todo: ffc4a0a63b78c956f272c957ef9d16bef0505297

**Comment by txomon** [comment]
@fravalpin Los timestamps están como metadata de los ficheros. Si abres con un visualizador de fotos, en detalles, te aparece la fecha en la que fue sacada. Si la subes a google photos o sitios así, Google te la categoriza respecto a eso.

**Comment by inlacou** [comment]
Probado una vez más desde cero.

Quizas sea mi deficiente conexión a internet, pero parece que si no creo a mano la carpeta "dl" no funciona. Cuando la he creado ha funcionado, vaya.

**Comment by txomon** [comment]
@Inlacou Creo que en este caso estás ejecutando una versión antigua, asegurate de que has hecho python setup.py install =)

Por cierto, si me prestas tus servicios como tester más veces, utiliza python setup.py develop, así con solo hacer un git pull se te actualiza lo que se ejecuta (se hace un link al sitio en el que hayas descargado)

**Comment by inlacou** [comment]
Cada vez que haces un commit creo una nueva carpeta y hago un nuevo clone. Supongo que si hago el develop que comentas, podría ahorrarmelo y usar el git pull. ¿Va de eso el tema, o me equivoco?

En cualquier caso, encantado de aportar mi granito de arena haciendo de tester :).

**Comment by txomon** [comment]
@Inlacou He actualizado el readme con instrucciones paso a paso 0c4e38bf70848e675e1ce19112d91f33821ebe1e

**Comment by txomon** [comment]
Marco como solucionado el issue...
